# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Root
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1

  - package-ecosystem: "npm"
    directory: "/" # Single root package and pnpm lockfile
    open-pull-requests-limit: 20
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    cooldown:
      default-days: 1
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
          - "@fastify/otel"
      typescript:
        patterns:
          - "@voxpelli/tsconfig"
          - "@types/node"
          - "typescript"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
          - "neostandard"
      jsdom:
        patterns:
          - "jsdom"
          - "@types/jsdom"

  # Shared API/worker image
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1
