#!/usr/bin/env bash

set -e

# Get the current branch name
TARGET_BRANCH=$(git branch --show-current)
BRANCH_NAME="regenerate-lockfile-${GITHUB_RUN_NUMBER:-$(date +%s)}"

echo "🎯 Target branch: $TARGET_BRANCH"

# Configure git
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

# Delete existing package-lock.json
echo "🗑️  Deleting existing package-lock.json..."
rm -f package-lock.json

# Run npm install to generate new lockfile
echo "📦 Running npm install..."
npm install

# Check if there are changes
if git diff --exit-code package-lock.json > /dev/null 2>&1; then
  echo "✅ No changes detected in package-lock.json"
  exit 0
fi

echo "📝 Changes detected in package-lock.json"

# Create a new branch
echo "🌿 Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# Stage changes
git add package-lock.json

# Generate commit message with Copilot if available
COMMIT_MESSAGE="chore: regenerate package-lock.json"
if command -v gh &> /dev/null && gh extension list | grep -q copilot; then
  echo "🤖 Generating commit message with GitHub Copilot..."

  # Get the diff stats
  DIFF_STAT=$(git diff --staged --stat package-lock.json)

  # Create prompt for Copilot
  PROMPT="Write a concise git commit message for the following changes to package-lock.json. Use conventional commit format. The file was regenerated by deleting and running npm install.

Changes:
${DIFF_STAT}

Respond with ONLY the commit message, nothing else."

  # Try to get suggestion from Copilot (suppress errors if it fails)
  SUGGESTED_MESSAGE=$(gh copilot suggest -t shell "git commit -m '${PROMPT}'" 2>/dev/null | grep -o '".*"' | sed 's/"//g' || echo "")

  if [ -n "$SUGGESTED_MESSAGE" ]; then
    COMMIT_MESSAGE="$SUGGESTED_MESSAGE"
    echo "✨ Using Copilot-generated message: $COMMIT_MESSAGE"
  else
    echo "ℹ️  Copilot suggestion failed, using default message"
  fi
else
  echo "ℹ️  GitHub Copilot CLI not available, using default message"
fi

# Commit changes
echo "💾 Committing changes..."
git commit -m "$COMMIT_MESSAGE"

# Push the branch
echo "⬆️  Pushing branch to origin..."
git push origin "$BRANCH_NAME"

# Create PR body
PR_BODY="This PR was automatically generated by the regenerate-lockfile workflow.

The package-lock.json file has been regenerated by deleting the existing lockfile and running \`npm install\`.

Please review the changes before merging.

Triggered by: @${GITHUB_ACTOR:-unknown}
Run number: ${GITHUB_RUN_NUMBER:-N/A}
Base branch: $TARGET_BRANCH"

# Create PR using GitHub CLI
echo "🔀 Creating pull request..."
gh pr create \
  --base "$TARGET_BRANCH" \
  --head "$BRANCH_NAME" \
  --title "$COMMIT_MESSAGE" \
  --body "$PR_BODY"

echo "✅ Pull request created successfully"
