#!/usr/bin/env bash

set -euo pipefail

# Get the current branch name
TARGET_BRANCH=$(git --no-pager branch --show-current)
BRANCH_NAME="regenerate-lockfile-${GITHUB_RUN_NUMBER:-$(date +%s)}"

echo "🎯 Target branch: $TARGET_BRANCH"

# Configure git
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

# Capture outdated packages before regenerating
echo "📊 Checking for outdated packages..."
OUTDATED_BEFORE=$(pnpm outdated || true)

# Resolve from scratch, not the installed tree's hidden lockfile.
echo "🗑️  Removing the old lockfile and installed tree..."
rm -f pnpm-lock.yaml
rm -rf node_modules

echo "📦 Resolving dependencies with the native pnpm patch/settings policy..."
pnpm install --no-frozen-lockfile
node scripts/verify-giscus-patch.js

# Prove the generated lockfile reproduces a clean, patched installation.
rm -rf node_modules
pnpm install --frozen-lockfile
node scripts/verify-giscus-patch.js
pnpm run build
node scripts/verify-giscus-patch.js --built

# Capture outdated packages after regenerating
OUTDATED_AFTER=$(pnpm outdated || true)

# Check if there are changes
if git --no-pager diff --exit-code pnpm-lock.yaml > /dev/null 2>&1; then
  echo "✅ No changes detected in pnpm-lock.yaml"
  exit 0
fi

echo "📝 Changes detected in pnpm-lock.yaml"

# Create a new branch
echo "🌿 Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# Stage changes
git add pnpm-lock.yaml

# Get the diff stats
DIFF_STAT=$(git --no-pager diff --staged --stat pnpm-lock.yaml)

# Build commit message with formatted diff
COMMIT_MESSAGE="chore: regenerate pnpm-lock.yaml

\`\`\`diff
${DIFF_STAT}
\`\`\`"

if [ -n "$OUTDATED_BEFORE" ]; then
  COMMIT_MESSAGE="${COMMIT_MESSAGE}

Outdated packages before regeneration:
${OUTDATED_BEFORE}"
fi

# Commit changes
echo "💾 Committing changes..."
GIT_EDITOR=true git commit -m "$COMMIT_MESSAGE"

# Push the branch
echo "⬆️  Pushing branch to origin..."
git push origin "$BRANCH_NAME"

# Build PR body with outdated package information
PR_BODY="## 🔄 Regenerate pnpm-lock.yaml

This PR was automatically generated by the regenerate-lockfile workflow.

The root \`pnpm-lock.yaml\` was freshly resolved without an existing installed tree or lockfile.
A clean frozen-lockfile install and browser build verified the native Giscus patch.
Dependency ranges, release-age rules, package extensions, and build-script policies remain unchanged.

### 📊 Changes

\`\`\`diff
${DIFF_STAT}
\`\`\`"

if [ -n "$OUTDATED_BEFORE" ]; then
  PR_BODY="${PR_BODY}

### 📦 Outdated Packages (Before Regeneration)

\`\`\`
${OUTDATED_BEFORE}
\`\`\`"
fi

if [ -n "$OUTDATED_AFTER" ] && [ "$OUTDATED_AFTER" != "$OUTDATED_BEFORE" ]; then
  PR_BODY="${PR_BODY}

### 📦 Outdated Packages (After Regeneration)

\`\`\`
${OUTDATED_AFTER}
\`\`\`"
fi

PR_BODY="${PR_BODY}

---

**Triggered by:** @${GITHUB_ACTOR:-unknown}
**Run number:** ${GITHUB_RUN_NUMBER:-N/A}
**Base branch:** ${TARGET_BRANCH}"

# Create PR using GitHub CLI
echo "🔀 Creating pull request..."
gh pr create \
  --base "$TARGET_BRANCH" \
  --head "$BRANCH_NAME" \
  --title "chore: regenerate pnpm-lock.yaml" \
  --body "$PR_BODY"

echo "✅ Pull request created successfully"
