packages:
  - packages/*

injectWorkspacePackages: true

catalog:
  "@bret/is-youtube-url": ^1.0.5
  "@fastify/autoload": ^6.0.1
  "@fastify/env": ^5.0.1
  "@fastify/otel": ^0.16.0
  "@fastify/postgres": ^6.0.2
  "@fastify/redis": ^7.1.0
  "@fastify/sensible": ^6.0.1
  "@fastify/type-provider-json-schema-to-ts": ^5.0.0
  "@nearform/sql": ^1.10.5
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/exporter-prometheus": ^0.209.0
  "@opentelemetry/host-metrics": ^0.38.0
  "@opentelemetry/instrumentation-http": ^0.209.0
  "@opentelemetry/instrumentation-runtime-node": ^0.22.0
  "@opentelemetry/sdk-node": ^0.209.0
  "@types/node": ^25.0.8
  "@types/jsdom": ^27.0.0
  "@types/pg": ^8.11.10
  "@voxpelli/tsconfig": ^16.0.0
  abstract-cache-redis: ^2.0.0
  c8: ^10.0.0
  eslint: ^9.39.1
  fastify: ^5.0.0
  fastify-cli: ^7.0.1
  fastify-healthcheck: ^5.0.0
  fastify-plugin: ^5.0.1
  jsdom: ^28.0.0
  neostandard: ^0.12.0
  npm-run-all2: ^8.0.1
  pg: ^8.16.3
  typescript: ~5.9.0
  stripe: ^20.3.1
  # bad type errors above 7.16.0. Hold off a bit
  undici: 7.16.0

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - protobufjs

patchedDependencies:
  giscus@1.6.0: patches/giscus@1.6.0.patch
