packages:
  - packages/*

injectWorkspacePackages: true

catalog:
  "@fastify/autoload": ^6.0.1
  "@fastify/env": ^5.0.1
  "@fastify/otel": ^0.16.0
  "@fastify/postgres": ^6.0.2
  "@fastify/redis": ^7.1.0
  "@fastify/sensible": ^6.0.1
  "@fastify/type-provider-json-schema-to-ts": ^5.0.0
  "@nearform/sql": ^1.10.5
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/exporter-prometheus": ^0.208.0
  "@opentelemetry/host-metrics": ^0.37.0
  "@opentelemetry/instrumentation-http": ^0.208.0
  "@opentelemetry/instrumentation-runtime-node": ^0.22.0
  "@opentelemetry/sdk-node": ^0.208.0
  "@types/node": ^24.9.1
  "@types/pg": ^8.11.10
  "@voxpelli/tsconfig": ^16.0.0
  abstract-cache-redis: ^2.0.0
  c8: ^10.0.0
  eslint: ^9.39.1
  fastify: ^5.0.0
  fastify-cli: ^7.0.1
  fastify-healthcheck: ^5.0.0
  fastify-plugin: ^5.0.1
  neostandard: ^0.12.0
  npm-run-all2: ^8.0.1
  pg: ^8.16.3
  typescript: ~5.9.0
  # bad type errors above 7.16.0. Hold off a bit
  undici: 7.16.0

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - protobufjs

patchedDependencies:
  giscus@1.6.0: patches/giscus@1.6.0.patch
